reload:
  name: Reload Mapping File
  description: Reload mapping file.

trigger:
  name: Trigger Mapping
  description: Simulate the triggering of a Z-Wave scene.
  fields:
    zw_network:
      name: Z-Wave Network ID (home_id)
      required: true
      example: "4227869312"
      selector:
        text: {}
    zw_scene:
      name: Z-Wave Scene Value (0-255)
      required: true
      example: "15"
      selector:
        number:
          min: 0
          max: 255
          step: 1
          mode: box
